// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CollectionMeta struct {
	Number        int  `json:"number"`
	Size          int  `json:"size"`
	TotalElements int  `json:"totalElements"`
	TotalPages    int  `json:"totalPages"`
	HasNextPage   bool `json:"hasNextPage"`
	HasPrevPage   bool `json:"hasPrevPage"`
}

type CreatePlanInput struct {
	Name     string `json:"name"`
	CPUCores int    `json:"cpuCores"`
	RAMMb    int    `json:"ramMb"`
	DiskGb   int    `json:"diskGb"`
}

type Mutation struct {
}

type OrderServerInput struct {
	PlanID string `json:"planId"`
	Name   string `json:"name"`
}

type Plan struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CPUCores int    `json:"cpuCores"`
	RAMMb    int    `json:"ramMB"`
	DiskGb   int    `json:"diskGB"`
}

type PlanCollection struct {
	Plans []*Plan         `json:"plans"`
	Meta  *CollectionMeta `json:"meta"`
}

type Query struct {
}

type Server struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Status      ServerStatus `json:"status"`
	PlanID      string       `json:"planId"`
	IPv4Address *string      `json:"IPv4Address,omitempty"`
	CreatedAt   string       `json:"createdAt"`
	Plan        *Plan        `json:"plan,omitempty"`
}

type ServerCollection struct {
	Servers []*Server       `json:"servers"`
	Meta    *CollectionMeta `json:"meta"`
}

type ServerAction string

const (
	ServerActionStart  ServerAction = "START"
	ServerActionStop   ServerAction = "STOP"
	ServerActionDelete ServerAction = "DELETE"
)

var AllServerAction = []ServerAction{
	ServerActionStart,
	ServerActionStop,
	ServerActionDelete,
}

func (e ServerAction) IsValid() bool {
	switch e {
	case ServerActionStart, ServerActionStop, ServerActionDelete:
		return true
	}
	return false
}

func (e ServerAction) String() string {
	return string(e)
}

func (e *ServerAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServerAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServerAction", str)
	}
	return nil
}

func (e ServerAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServerAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServerAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServerStatus string

const (
	ServerStatusPending         ServerStatus = "PENDING"
	ServerStatusRunning         ServerStatus = "RUNNING"
	ServerStatusStopped         ServerStatus = "STOPPED"
	ServerStatusProvisionFailed ServerStatus = "PROVISION_FAILED"
)

var AllServerStatus = []ServerStatus{
	ServerStatusPending,
	ServerStatusRunning,
	ServerStatusStopped,
	ServerStatusProvisionFailed,
}

func (e ServerStatus) IsValid() bool {
	switch e {
	case ServerStatusPending, ServerStatusRunning, ServerStatusStopped, ServerStatusProvisionFailed:
		return true
	}
	return false
}

func (e ServerStatus) String() string {
	return string(e)
}

func (e *ServerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServerStatus", str)
	}
	return nil
}

func (e ServerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
