package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"hosting-kit/auth"
	"hosting-kit/page"
	"hosting-service/internal/plan"
	"hosting-service/internal/server"

	"github.com/google/uuid"
)

// CreatePlan is the resolver for the createPlan field.
func (r *mutationResolver) CreatePlan(ctx context.Context, input CreatePlanInput) (*Plan, error) {
	claims, err := auth.GetClaims(ctx)
	if err != nil {
		return nil, err
	}

	if !claims.IsAdmin {
		return nil, auth.ErrForbidden
	}

	newPlan, err := r.PlanBus.Create(ctx, plan.CreatePlanParams{
		Name:     input.Name,
		CPUCores: input.CPUCores,
		RAMMB:    input.RAMMb,
		DiskGB:   input.DiskGb,
	})

	if err != nil {
		if errors.Is(err, plan.ErrValidation) {
			return nil, err
		}
		return nil, errors.New("internal server error")
	}

	return toPlan(newPlan), nil
}

// OrderServer is the resolver for the orderServer field.
func (r *mutationResolver) OrderServer(ctx context.Context, input OrderServerInput) (*Server, error) {
	claims, err := auth.GetClaims(ctx)
	if err != nil {
		return nil, err
	}

	planUUID, err := uuid.Parse(input.PlanID)
	if err != nil {
		return nil, errors.New("invalid plan ID format")
	}

	newServer, err := r.ServerBus.Create(ctx, input.Name, planUUID, claims.UserID)
	if err != nil {
		if errors.Is(err, plan.ErrPlanNotFound) {
			return nil, err
		}
		if errors.Is(err, server.ErrValidation) {
			return nil, err
		}
		return nil, errors.New("internal server error")
	}

	return toServer(newServer), nil
}

// ManageServer is the resolver for the manageServer field.
func (r *mutationResolver) ManageServer(ctx context.Context, serverID string, action ServerAction) (*Server, error) {
	claims, err := auth.GetClaims(ctx)
	if err != nil {
		return nil, err
	}

	serverUUID, err := uuid.Parse(serverID)
	if err != nil {
		return nil, errors.New("invalid server ID format")
	}

	var currentServer server.Server

	switch action {
	case ServerActionStart:
		currentServer, err = r.ServerBus.Start(ctx, serverUUID, claims.UserID)
	case ServerActionStop:
		currentServer, err = r.ServerBus.Stop(ctx, serverUUID, claims.UserID)
	case ServerActionDelete:
		currentServer, err = r.ServerBus.Delete(ctx, serverUUID, claims.UserID)
	default:
		return nil, fmt.Errorf("unknown action: %s", action)
	}

	if err != nil {
		if errors.Is(err, server.ErrServerNotFound) {
			return nil, err
		}
		if errors.Is(err, server.ErrValidation) {
			return nil, err
		}
		return nil, errors.New("internal server error")
	}

	return toServer(currentServer), nil
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context, pg int, ps int) (*PlanCollection, error) {
	parsedPage := page.Parse(pg, ps)
	plans, count, err := r.PlanBus.Search(ctx, parsedPage)
	if err != nil {
		return nil, errors.New("internal server error")
	}

	return toPlanCollection(plans, parsedPage, count), nil
}

// Servers is the resolver for the servers field.
func (r *queryResolver) Servers(ctx context.Context, pg int, ps int) (*ServerCollection, error) {
	claims, err := auth.GetClaims(ctx)
	if err != nil {
		return nil, err
	}

	parsedPage := page.Parse(pg, ps)
	servers, count, err := r.ServerBus.Search(ctx, parsedPage, claims.UserID)
	if err != nil {
		return nil, errors.New("internal server error")
	}

	return toServerCollection(servers, parsedPage, count), nil
}

// Plan is the resolver for the plan field.
func (r *queryResolver) Plan(ctx context.Context, id string) (*Plan, error) {
	planUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid plan ID format")
	}

	newPlan, err := r.PlanBus.FindByID(ctx, planUUID)
	if err != nil {
		if errors.Is(err, plan.ErrPlanNotFound) {
			return nil, err
		}
		return nil, errors.New("internal server error")
	}

	return toPlan(newPlan), nil
}

// Server is the resolver for the server field.
func (r *queryResolver) Server(ctx context.Context, id string) (*Server, error) {
	claims, err := auth.GetClaims(ctx)
	if err != nil {
		return nil, err
	}

	serverUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid server ID format")
	}

	newServer, err := r.ServerBus.FindByID(ctx, serverUUID, claims.UserID)
	if err != nil {
		if errors.Is(err, server.ErrServerNotFound) {
			return nil, err
		}
		return nil, errors.New("internal server error")
	}

	return toServer(newServer), nil
}

// Plan is the resolver for the plan field.
func (r *serverResolver) Plan(ctx context.Context, obj *Server) (*Plan, error) {
	planUUID, err := uuid.Parse(obj.PlanID)
	if err != nil {
		return nil, errors.New("invalid plan ID format")
	}

	newPlan, err := r.PlanBus.FindByID(ctx, planUUID)
	if err != nil {
		if errors.Is(err, plan.ErrPlanNotFound) {
			return nil, nil
		}
		return nil, errors.New("internal server error")
	}

	return toPlan(newPlan), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Server returns ServerResolver implementation.
func (r *Resolver) Server() ServerResolver { return &serverResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type serverResolver struct{ *Resolver }
