// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreatePlanInput struct {
	Name     string `json:"name"`
	CPUCores int    `json:"cpuCores"`
	RAMMb    int    `json:"ramMb"`
	DiskGb   int    `json:"diskGb"`
}

type Mutation struct {
}

type OrderServerInput struct {
	PlanID string `json:"planId"`
	Name   string `json:"name"`
}

type Plan struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CPUCores int    `json:"cpuCores"`
	RAMMb    int    `json:"ramMb"`
	DiskGb   int    `json:"diskGb"`
}

type PlanCollection struct {
	Plans         []*Plan `json:"plans"`
	TotalElements int     `json:"totalElements"`
	TotalPages    int     `json:"totalPages"`
	CurrentPage   int     `json:"currentPage"`
	HasNextPage   bool    `json:"hasNextPage"`
}

type Query struct {
}

type Server struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Status    ServerStatus `json:"status"`
	PlanID    string       `json:"planId"`
	CreatedAt string       `json:"createdAt"`
	Plan      *Plan        `json:"plan,omitempty"`
}

type ServerCollection struct {
	Servers       []*Server `json:"servers"`
	TotalElements int       `json:"totalElements"`
	TotalPages    int       `json:"totalPages"`
	CurrentPage   int       `json:"currentPage"`
	HasNextPage   bool      `json:"hasNextPage"`
}

type ServerStatus string

const (
	ServerStatusPending   ServerStatus = "PENDING"
	ServerStatusRunning   ServerStatus = "RUNNING"
	ServerStatusStopped   ServerStatus = "STOPPED"
	ServerStatusRebooting ServerStatus = "REBOOTING"
	ServerStatusDeleting  ServerStatus = "DELETING"
)

var AllServerStatus = []ServerStatus{
	ServerStatusPending,
	ServerStatusRunning,
	ServerStatusStopped,
	ServerStatusRebooting,
	ServerStatusDeleting,
}

func (e ServerStatus) IsValid() bool {
	switch e {
	case ServerStatusPending, ServerStatusRunning, ServerStatusStopped, ServerStatusRebooting, ServerStatusDeleting:
		return true
	}
	return false
}

func (e ServerStatus) String() string {
	return string(e)
}

func (e *ServerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServerStatus", str)
	}
	return nil
}

func (e ServerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
